### ISSUE TITLE
Menu - create New Lead

### ISSUE THREAD

**Issue by neternefer** [EN-IH-WDPT-JUN21/TKWRN-Microservices-CRM#17]

**Comment by neternefer** [comment]
New Lead is created and saved but the input validation doesn't work and starts infinite loop after salesRep
![inputValidation](https://user-images.githubusercontent.com/7143565/140622797-87b0d122-2276-4dce-a83b-9809ae450d09.png)

**Comment by Omakatayo** [comment]
Works
